org.jeasy.rules.core.DefaultRulesEngine.java NullPointerException #329
j-easy/easy-rules pull request #330
Opened 2021-01-31 07:17 UTC by aston2016

2021-02-08 20:36 UTC, benas requested changes

2021-02-08 20:36 UTC, benas commented on easy-rules-core/src/main/java/org/jeasy/rules/core/DefaultRulesEngine.java
> +        if (Objects.isNull(facts)){
We should not accept `null` in the first place. Please update the PR and add `Objects.requireNonNull` for the `Rules` and `Facts` parameters in `fire` and `check` methods.

2021-02-08 21:06 UTC, benas commented
Thank you for raising this issue and opening this PR 👍  I think we need to add null checks for rules and facts parameters in the `check` and `fire` methods. The same issue would happen in `InferenceRulesEngine` which I fixed in 8109230ca08adbc69d9a889cf80e399247652b79. Don't hesitate to add your name to the contributors list in the README as well! Thank you upfront.

2021-02-10 13:29 UTC, aston2016 commented
Thank you for your reply.
I will resubmit later.
I wish you a happy Chinese New Year.

2021-02-10 14:05 UTC, closed without merging